name: Test

on: [push]

jobs:
  mac:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build server
        run: go build -v cmd/datajar-server/main.go

      - name: Run tests
        run: go test -v ./...

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build systemd credential server
        run: go build -v cmd/datajar-credential-server/main.go

      - name: Run tests
        run: go test -v ./...
