name: Test

on: [push]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binary
        run: go build -v cmd/datajar-server/main.go

      - name: Run tests
        run: go test -v ./internal/server
